#!/usr/bin/env python3
"""Generate Engineering Navigator index.md pages from specification.yaml files."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError as exc:
    raise SystemExit(
        "PyYAML is required. Install it with: python -m pip install pyyaml"
    ) from exc

GENERATED_MARKER = "<!-- generated-by: engineering-navigator-generator-v1 -->"

REQUIRED_FIELDS = {
    "id": str,
    "title": str,
    "status": str,
    "repository": str,
    "engineering_object": str,
    "objective": str,
    "current_status": str,
    "depends_on": list,
    "supports": list,
    "reading_points": list,
    "engineering_sessions": list,
    "engineering_artifacts": list,
    "generated_figures": list,
    "primary_sources": list,
    "future_sources": list,
    "current_questions": list,
    "next_engineering_driver": list,
}


class SpecificationError(ValueError):
    """Raised where an Engineering Navigator specification is invalid."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate index.md pages from Engineering Navigator specification.yaml files."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("engineering_navigator"),
        help="Engineering Navigator directory (default: engineering_navigator).",
    )
    parser.add_argument(
        "--driver",
        action="append",
        default=[],
        help="Generate only this driver id. Repeat for multiple drivers.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write generated index.md files. Without this flag, show diffs only.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow replacement of an index.md not previously generated by this tool.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any generated page is missing or outdated.",
    )
    return parser.parse_args()


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise SpecificationError(f"{path}: invalid YAML: {exc}") from exc
    if not isinstance(raw, dict):
        raise SpecificationError(f"{path}: expected one top-level mapping")
    return raw


def validate_specification(spec: dict[str, Any], path: Path) -> None:
    for field, expected_type in REQUIRED_FIELDS.items():
        if field not in spec:
            raise SpecificationError(f"{path}: missing required field {field!r}")
        if not isinstance(spec[field], expected_type):
            raise SpecificationError(
                f"{path}: field {field!r} must be {expected_type.__name__}"
            )

    driver_id = spec["id"]
    if not re.fullmatch(r"[a-z0-9]+(?:_[a-z0-9]+)*", driver_id):
        raise SpecificationError(
            f"{path}: id must use lowercase snake_case: {driver_id!r}"
        )
    if path.parent.name != driver_id:
        raise SpecificationError(
            f"{path}: directory {path.parent.name!r} must match id {driver_id!r}"
        )

    list_fields = [
        "depends_on",
        "supports",
        "reading_points",
        "engineering_sessions",
        "engineering_artifacts",
        "generated_figures",
        "primary_sources",
        "future_sources",
        "current_questions",
        "next_engineering_driver",
    ]
    for field in list_fields:
        values = spec[field]
        if any(not isinstance(value, str) or not value.strip() for value in values):
            raise SpecificationError(
                f"{path}: field {field!r} must contain nonempty strings"
            )
        if len(values) != len(set(values)):
            raise SpecificationError(f"{path}: field {field!r} contains duplicates")


def humanize(identifier: str) -> str:
    special = {"tes": "TES", "tc": "Tc", "si": "Si", "inl": "INL", "ga": "GA"}
    words = identifier.replace("-", "_").split("_")
    return " ".join(special.get(word.lower(), word.capitalize()) for word in words)


def driver_link(identifier: str, known_driver_ids: set[str]) -> str:
    label = humanize(identifier)
    if identifier in known_driver_ids:
        return f"[{label}](../{identifier}/)"
    return f"`{identifier}`"


def code_items(values: list[str]) -> str:
    return "_None recorded._" if not values else "\n".join(f"- `{v}`" for v in values)


def text_items(values: list[str]) -> str:
    return "_None recorded._" if not values else "\n".join(f"- {v}" for v in values)


def driver_items(values: list[str], known_driver_ids: set[str]) -> str:
    if not values:
        return "_None recorded._"
    return "\n".join(f"- {driver_link(v, known_driver_ids)}" for v in values)


def render_markdown(spec: dict[str, Any], known_driver_ids: set[str]) -> str:
    status = spec["status"].strip().capitalize()
    parts = [
        GENERATED_MARKER,
        f"# {spec['title']}",
        "",
        "**Engineering Driver**  ",
        f"**Status:** {status}  ",
        f"**Repository:** `{spec['repository']}`  ",
        f"**Engineering Object:** {spec['engineering_object']}",
        "",
        "---",
        "",
        "## Engineering Objective",
        "",
        spec["objective"].strip(),
        "",
        "---",
        "",
        "## Current Status",
        "",
        spec["current_status"].strip(),
        "",
        "---",
        "",
        "## Engineering Dependencies",
        "",
        driver_items(spec["depends_on"], known_driver_ids),
        "",
        "---",
        "",
        "## Engineering Outcomes",
        "",
        driver_items(spec["supports"], known_driver_ids),
        "",
        "---",
        "",
        "## Supporting Evidence",
        "",
        "### Reading Points",
        "",
        code_items(spec["reading_points"]),
        "",
        "### Engineering Sessions",
        "",
        code_items(spec["engineering_sessions"]),
        "",
        "### Engineering Artifacts",
        "",
        code_items(spec["engineering_artifacts"]),
        "",
        "### Generated Figures",
        "",
        code_items(spec["generated_figures"]),
        "",
        "---",
        "",
        "## Primary Sources",
        "",
        text_items(spec["primary_sources"]),
        "",
        "---",
        "",
        "## Future Sources",
        "",
        text_items(spec["future_sources"]),
        "",
        "---",
        "",
        "## Current Engineering Questions",
        "",
        text_items(spec["current_questions"]),
        "",
        "---",
        "",
        "## Next Engineering Driver",
        "",
        driver_items(spec["next_engineering_driver"], known_driver_ids),
        "",
        "---",
        "",
        "*Admissible generalizations trail leading specifications.*",
        "",
    ]
    return "\n".join(parts)


def discover_specifications(root: Path) -> list[Path]:
    return sorted(root.glob("*/specification.yaml"))


def select_specifications(paths: list[Path], requested: list[str]) -> list[Path]:
    if not requested:
        return paths
    requested_set = set(requested)
    selected = [p for p in paths if p.parent.name in requested_set]
    missing = sorted(requested_set - {p.parent.name for p in selected})
    if missing:
        raise SpecificationError(
            "No specification.yaml found for driver(s): " + ", ".join(missing)
        )
    return selected


def print_diff(path: Path, expected: str) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    diff = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=str(path),
        tofile=f"{path} (generated)",
        lineterm="",
    )
    print("\n".join(diff))


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    if not root.exists():
        raise SpecificationError(f"Engineering Navigator root does not exist: {root}")

    all_paths = discover_specifications(root)
    if not all_paths:
        raise SpecificationError(f"No specification.yaml files found under {root}")

    all_specs: dict[str, dict[str, Any]] = {}
    for path in all_paths:
        spec = load_yaml(path)
        validate_specification(spec, path)
        if spec["id"] in all_specs:
            raise SpecificationError(f"Duplicate driver id: {spec['id']}")
        all_specs[spec["id"]] = spec

    selected_paths = select_specifications(all_paths, args.driver)
    known_driver_ids = set(all_specs)
    changed = 0

    for spec_path in selected_paths:
        spec = all_specs[spec_path.parent.name]
        output_path = spec_path.parent / "index.md"
        expected = render_markdown(spec, known_driver_ids)
        current = output_path.read_text(encoding="utf-8") if output_path.exists() else None

        if current == expected:
            print(f"unchanged: {output_path.relative_to(root.parent)}")
            continue

        changed += 1
        if args.check:
            print(f"outdated: {output_path.relative_to(root.parent)}")
            continue
        if not args.write:
            print_diff(output_path, expected)
            continue

        if output_path.exists() and GENERATED_MARKER not in output_path.read_text(encoding="utf-8") and not args.force:
            raise SpecificationError(
                f"{output_path} was not generated by this tool. Use --force to replace it."
            )

        output_path.write_text(expected, encoding="utf-8")
        print(f"generated: {output_path.relative_to(root.parent)}")

    if args.check and changed:
        print(f"{changed} generated page(s) are missing or outdated.", file=sys.stderr)
        return 1
    if not args.write and not args.check:
        print("\nPreview only. Re-run with --write to generate files.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SpecificationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)
