#!/usr/bin/env python3
"""Generate engineering_navigator/graph.md from engineering_graph.yaml."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError as exc:
    raise SystemExit(
        "PyYAML is required. Install it with: python -m pip install pyyaml"
    ) from exc

GENERATED_MARKER = "<!-- generated-by: generate-engineering-graph-page-v1 -->"


class GraphPageError(ValueError):
    """Raised where the Engineering Graph cannot be rendered."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate engineering_navigator/graph.md from engineering_graph.yaml."
    )
    parser.add_argument(
        "--graph",
        type=Path,
        default=Path("engineering_navigator/engineering_graph.yaml"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("engineering_navigator/graph.md"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 where graph.md is missing or outdated.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing graph.md not previously generated by this tool.",
    )
    return parser.parse_args()


def load_graph(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise GraphPageError(f"Engineering Graph does not exist: {path}")

    try:
        graph = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise GraphPageError(f"{path}: invalid YAML: {exc}") from exc

    if not isinstance(graph, dict):
        raise GraphPageError(f"{path}: expected one top-level mapping")

    for field in ("graph", "drivers", "relationships"):
        if field not in graph:
            raise GraphPageError(f"{path}: missing top-level field {field!r}")

    return graph


def humanize(identifier: str) -> str:
    special = {"tes": "TES", "tc": "Tc", "si": "Si", "inl": "INL", "ga": "GA"}
    words = identifier.replace("-", "_").split("_")
    return " ".join(special.get(word.lower(), word.capitalize()) for word in words)


def driver_map(graph: dict[str, Any]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for driver in graph["drivers"]:
        if not isinstance(driver, dict):
            raise GraphPageError("Each driver must be a mapping")
        driver_id = driver.get("id")
        if not isinstance(driver_id, str) or not driver_id:
            raise GraphPageError("Each driver requires a nonempty id")
        if driver_id in result:
            raise GraphPageError(f"Duplicate driver id: {driver_id}")
        result[driver_id] = driver
    return result


def continuation_adjacency(
    graph: dict[str, Any], known_ids: set[str]
) -> dict[str, list[str]]:
    adjacency = {driver_id: [] for driver_id in known_ids}
    for edge in graph["relationships"]:
        if not isinstance(edge, dict) or edge.get("relation") != "continues_to":
            continue
        source = edge.get("source")
        target = edge.get("target")
        if source in known_ids and target in known_ids and target not in adjacency[source]:
            adjacency[source].append(target)
    return adjacency


def ordered_chains(
    graph: dict[str, Any], drivers: dict[str, dict[str, Any]]
) -> list[list[str]]:
    known_ids = set(drivers)
    adjacency = continuation_adjacency(graph, known_ids)

    incoming = {driver_id: 0 for driver_id in known_ids}
    for targets in adjacency.values():
        for target in targets:
            incoming[target] += 1

    starts = sorted(
        (driver_id for driver_id, count in incoming.items() if count == 0),
        key=lambda item: drivers[item].get("title", item),
    )

    chains: list[list[str]] = []
    visited: set[str] = set()

    def walk(start: str) -> list[str]:
        chain: list[str] = []
        current = start
        local_seen: set[str] = set()

        while current not in local_seen and current not in visited:
            chain.append(current)
            local_seen.add(current)
            visited.add(current)
            targets = adjacency.get(current, [])
            if len(targets) != 1:
                break
            current = targets[0]
        return chain

    for start in starts:
        chain = walk(start)
        if chain:
            chains.append(chain)

    for driver_id in sorted(
        known_ids - visited,
        key=lambda item: drivers[item].get("title", item),
    ):
        chain = walk(driver_id)
        if chain:
            chains.append(chain)

    return chains


def driver_link(driver: dict[str, Any]) -> str:
    driver_id = driver["id"]
    title = driver.get("title") or humanize(driver_id)
    return f"[{title}]({driver_id}/)"


def reading_points(driver: dict[str, Any]) -> str:
    values = driver.get("reading_points", [])
    return "—" if not values else ", ".join(f"`{value}`" for value in values)


def unresolved_ids(graph: dict[str, Any]) -> list[str]:
    ids: list[str] = []
    for item in graph.get("unresolved_driver_references", []):
        if not isinstance(item, dict):
            continue
        identifier = item.get("id")
        if isinstance(identifier, str) and identifier not in ids:
            ids.append(identifier)
    return sorted(ids, key=humanize)


def relationship_types(graph: dict[str, Any]) -> list[str]:
    values: list[str] = []
    for edge in graph["relationships"]:
        if not isinstance(edge, dict):
            continue
        relation = edge.get("relation")
        if isinstance(relation, str) and relation not in values:
            values.append(relation)

    preferred = ["supports", "continues_to", "navigates_to"]
    ordered = [item for item in preferred if item in values]
    ordered.extend(item for item in sorted(values) if item not in ordered)
    return ordered


def render_markdown(graph: dict[str, Any]) -> str:
    drivers = driver_map(graph)
    chains = ordered_chains(graph, drivers)
    metadata = graph["graph"]

    lines = [
        GENERATED_MARKER,
        "# Engineering Graph",
        "",
        "## Implemented Engineering Drivers",
        "",
    ]

    if not chains:
        lines.append("_No implemented Engineering Drivers recorded._")
    else:
        for index, chain in enumerate(chains):
            if index:
                lines.extend(["", "---", ""])
            for position, driver_id in enumerate(chain):
                lines.append(driver_link(drivers[driver_id]))
                if position < len(chain) - 1:
                    lines.extend(["", "↓", ""])

    lines.extend(
        [
            "",
            "---",
            "",
            "## Engineering Driver Overview",
            "",
            "| Driver | Status | Reading Points |",
            "|---|---|---|",
        ]
    )

    for driver in sorted(
        drivers.values(),
        key=lambda item: item.get("title", item["id"]),
    ):
        lines.append(
            f"| {driver_link(driver)} | "
            f"{str(driver.get('status', 'unknown')).capitalize()} | "
            f"{reading_points(driver)} |"
        )

    unresolved = unresolved_ids(graph)
    lines.extend(["", "---", "", "## Unresolved Engineering Drivers", ""])
    if unresolved:
        lines.extend(f"- `{identifier}`" for identifier in unresolved)
    else:
        lines.append("_None._")

    definitions = {
        "supports": "one Engineering Driver contributes to another.",
        "continues_to": "the engineering sequence advances to another driver.",
        "navigates_to": "the Navigator offers a direct continuation link.",
    }

    lines.extend(["", "---", "", "## Engineering Relationships", ""])
    relations = relationship_types(graph)
    if relations:
        for relation in relations:
            lines.append(
                f"- `{relation}` — "
                f"{definitions.get(relation, 'a relationship recorded by the Engineering Graph.')}"
            )
    else:
        lines.append("_None recorded._")

    lines.extend(
        [
            "",
            "---",
            "",
            "## Graph Summary",
            "",
            f"- Drivers: {metadata.get('driver_count', len(drivers))}",
            f"- Relationships: {metadata.get('edge_count', len(graph['relationships']))}",
            (
                "- Unresolved driver references: "
                f"{metadata.get('unresolved_reference_count', len(unresolved))}"
            ),
            "",
            "---",
            "",
            "Generated from `engineering_graph.yaml`.",
            "",
            "*Admissible generalizations trail leading specifications.*",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    graph_path = args.graph.resolve()
    output_path = args.output.resolve()

    graph = load_graph(graph_path)
    expected = render_markdown(graph)

    if args.check:
        if not output_path.exists():
            print(f"missing: {output_path}", file=sys.stderr)
            return 1
        if output_path.read_text(encoding="utf-8") != expected:
            print(f"outdated: {output_path}", file=sys.stderr)
            return 1
        print(f"verified: {output_path}")
        return 0

    if (
        output_path.exists()
        and GENERATED_MARKER not in output_path.read_text(encoding="utf-8")
        and not args.force
    ):
        raise GraphPageError(
            f"{output_path} was not generated by this tool. "
            "Use --force for the first replacement."
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    print(f"generated: {output_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GraphPageError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)
